import {ShoppingList} from './types';

export const shoppingListsData: ShoppingList[] = [
  {
    id: 1,
    name: 'Groceries',
    items: [
      {
        id: 1,
        name: 'Milk',
        quantity: 1,
        price: 1.5,
        isBought: true,
      },
      {
        id: 2,
        name: 'Bread',
        quantity: 2,
        price: 2,
        isBought: true,
      },
      {
        id: 3,
        name: 'Eggs',
        quantity: 12,
        price: 3,
        isBought: true,
      },
      {
        id: 4,
        name: 'Apples',
        quantity: 5,
        price: 4,
        isBought: false,
      },
      {
        id: 5,
        name: 'Bananas',
        quantity: 6,
        price: 1.2,
        isBought: false,
      },
      {
        id: 6,
        name: 'Potatoes',
        quantity: 10,
        price: 2.5,
        isBought: false,
      },
      {
        id: 7,
        name: 'Chicken',
        quantity: 2,
        price: 6,
        isBought: false,
      },
      {
        id: 8,
        name: 'Pasta',
        quantity: 3,
        price: 1.8,
        isBought: false,
      },
      {
        id: 9,
        name: 'Tomatoes',
        quantity: 4,
        price: 2.2,
        isBought: false,
      },
      {
        id: 10,
        name: 'Cereal',
        quantity: 1,
        price: 3.5,
        isBought: false,
      },
      {
        id: 11,
        name: 'Orange Juice',
        quantity: 2,
        price: 2.5,
        isBought: false,
      },
      {
        id: 12,
        name: 'Onions',
        quantity: 3,
        price: 1.0,
        isBought: false,
      },
      {
        id: 13,
        name: 'Coffee',
        quantity: 1,
        price: 5.0,
        isBought: false,
      },
      {
        id: 14,
        name: 'Peanut Butter',
        quantity: 1,
        price: 3.0,
        isBought: false,
      },
      {
        id: 15,
        name: 'Salad Greens',
        quantity: 2,
        price: 2.0,
        isBought: false,
      },
      {
        id: 16,
        name: 'Yogurt',
        quantity: 4,
        price: 1.8,
        isBought: false,
      },
      {
        id: 17,
        name: 'Ketchup',
        quantity: 1,
        price: 2.0,
        isBought: false,
      },
      {
        id: 18,
        name: 'Toothpaste',
        quantity: 1,
        price: 2.5,
        isBought: false,
      },
      {
        id: 19,
        name: 'Shampoo',
        quantity: 1,
        price: 3.0,
        isBought: false,
      },
      {
        id: 20,
        name: 'Toilet Paper',
        quantity: 6,
        price: 4.0,
        isBought: false,
      },
    ],
  },
  {
    id: 2,
    name: 'Office Supplies',
    items: [
      {
        id: 1,
        name: 'Notebook',
        quantity: 3,
        price: 5,
        isBought: false,
      },
      {
        id: 2,
        name: 'Pens',
        quantity: 10,
        price: 0.5,
        isBought: true,
      },
      {
        id: 3,
        name: 'Sticky Notes',
        quantity: 5,
        price: 1.5,
        isBought: true,
      },
    ],
  },
  {
    id: 3,
    name: 'Gardening',
    items: [
      {
        id: 1,
        name: 'Potting Soil',
        quantity: 2,
        price: 7,
        isBought: false,
      },
      {
        id: 2,
        name: 'Flower Seeds',
        quantity: 5,
        price: 1,
        isBought: false,
      },
      {
        id: 3,
        name: 'Watering Can',
        quantity: 1,
        price: 10,
        isBought: false,
      },
    ],
  },
];
